// app/dashboard/etilometros/data.js

export const etilometrosDados = [
  { 
    id: "ET-4269", 
    serie: "4269", 
    equipamento: "Alcotest Dräger", 
    cia: "Almoxarifado 17º BPM", 
    status: "Operacional", 
    marca: "Dräger", 
    modelo: "Alcotest", 
    patrimonioEtilometro: "100002378888",
    patrimonioImpressora: "100002379616",
    ultimaCalibracao: "20/05/2025", 
    proximaCalibracao: "20/05/2026", 
    numInmetro: "Portaria INMETRO", 
    responsavel: "Almoxarife", 
    observacoes: "Equipamento em carga no Almoxarifado central do Batalhão." 
  },
  { 
    id: "ET-5627", 
    serie: "5627", 
    equipamento: "Alcotest Dräger", 
    cia: "Almoxarifado 17º BPM", 
    status: "Manutenção", 
    marca: "Dräger", 
    modelo: "Alcotest", 
    patrimonioEtilometro: "100002385269",
    patrimonioImpressora: "100002385397",
    ultimaCalibracao: "18/11/2024", 
    proximaCalibracao: "18/11/2025", // Vencido conforme a planilha
    numInmetro: "Portaria INMETRO", 
    responsavel: "Almoxarife", 
    observacoes: "Retido no Almoxarifado. Aferição anual obrigatória INMETRO vencida." 
  },
  { 
    id: "ET-5625", 
    serie: "5625", 
    equipamento: "Alcotest Dräger", 
    cia: "Almoxarifado 17º BPM", 
    status: "Manutenção", 
    marca: "Dräger", 
    modelo: "Alcotest", 
    patrimonioEtilometro: "100002385264",
    patrimonioImpressora: "100002385392",
    ultimaCalibracao: "18/11/2024", 
    proximaCalibracao: "18/11/2025", 
    numInmetro: "Portaria INMETRO", 
    responsavel: "Almoxarife", 
    observacoes: "Retido no Almoxarifado. Necessita envio para laboratório da RBML." 
  },
  { 
    id: "ET-5696-ALM", 
    serie: "5696", 
    equipamento: "Alcotest Dräger", 
    cia: "Almoxarifado 17º BPM", 
    status: "Operacional", 
    marca: "Dräger", 
    modelo: "Alcotest", 
    patrimonioEtilometro: "100002385284",
    patrimonioImpressora: "100002385412",
    ultimaCalibracao: "20/05/2025", 
    proximaCalibracao: "20/05/2026", 
    numInmetro: "Portaria INMETRO", 
    responsavel: "Almoxarife", 
    observacoes: "Equipamento reserva pronto para substituição de carga." 
  },
  { 
    id: "ET-5662", 
    serie: "5662", 
    equipamento: "Alcotest Dräger", 
    cia: "Almoxarifado 17º BPM", 
    status: "Manutenção", 
    marca: "Dräger", 
    modelo: "Alcotest", 
    patrimonioEtilometro: "100002385338",
    patrimonioImpressora: "100002385466",
    ultimaCalibracao: "18/11/2024", 
    proximaCalibracao: "18/11/2025", 
    numInmetro: "Portaria INMETRO", 
    responsavel: "Almoxarife", 
    observacoes: "Aparelho aguardando cronograma de envio para calibração." 
  },
  { 
    id: "ET-3865", 
    serie: "3865", 
    equipamento: "Alcotest Dräger", 
    cia: "1ª Cia - Tijucas do Sul", 
    status: "Operacional", 
    marca: "Dräger", 
    modelo: "Alcotest", 
    patrimonioEtilometro: "100002378255",
    patrimonioImpressora: "100002378955",
    ultimaCalibracao: "20/05/2025", 
    proximaCalibracao: "20/05/2026", 
    numInmetro: "Portaria INMETRO", 
    responsavel: "Sgt. Comandante Destacamento", 
    observacoes: "Alocado no destacamento de Tijucas do Sul. Operação normal." 
  },
  { 
    id: "ET-5696-SJP", 
    serie: "5696", 
    equipamento: "Alcotest Dräger", 
    cia: "1ª Cia - São José dos Pinhais", 
    status: "Operacional", 
    marca: "Dräger", 
    modelo: "Alcotest", 
    patrimonioEtilometro: "100002385284",
    patrimonioImpressora: "100002385412",
    ultimaCalibracao: "20/05/2025", 
    proximaCalibracao: "20/05/2026", 
    numInmetro: "Portaria INMETRO", 
    responsavel: "Sgt. Supervisor da Cia", 
    observacoes: "Alocado na Sede da 1ª Companhia (São José dos Pinhais)." 
  },
  { 
    id: "ET-5652", 
    serie: "5652", 
    equipamento: "Alcotest Dräger", 
    cia: "2ª Cia - Araucária", 
    status: "Operacional", 
    marca: "Dräger", 
    modelo: "Alcotest", 
    patrimonioEtilometro: "100002385380",
    patrimonioImpressora: "100002385508",
    ultimaCalibracao: "20/05/2025", 
    proximaCalibracao: "20/05/2026", 
    numInmetro: "Portaria INMETRO", 
    responsavel: "Sgt. Supervisor Araucária", 
    observacoes: "Carga operacional efetiva no município de Araucária." 
  },
  { 
    id: "ET-5326", 
    serie: "5326", 
    equipamento: "Alcotest Dräger", 
    cia: "3ª Cia - Campo Largo", 
    status: "Operacional", 
    marca: "Dräger", 
    modelo: "Alcotest", 
    patrimonioEtilometro: "100002384418",
    patrimonioImpressora: "100002384546",
    ultimaCalibracao: "20/05/2025", 
    proximaCalibracao: "20/05/2026", 
    numInmetro: "Portaria INMETRO", 
    responsavel: "Sgt. Supervisor Campo Largo", 
    observacoes: "Equipamento operando na área da 3ª Cia." 
  },
  { 
    id: "ET-4269-FRG", 
    serie: "4269", 
    equipamento: "Alcotest Dräger", 
    cia: "4ª Cia - Fazenda Rio Grande", 
    status: "Operacional", 
    marca: "Dräger", 
    modelo: "Alcotest", 
    patrimonioEtilometro: "100002378888",
    patrimonioImpressora: "100002379616",
    ultimaCalibracao: "20/05/2025", 
    proximaCalibracao: "20/05/2026", 
    numInmetro: "Portaria INMETRO", 
    responsavel: "Sgt. Supervisor FRG", 
    observacoes: "Carga setorial da 4ª Companhia." 
  },
  { 
    id: "ET-5704", 
    serie: "5704", 
    equipamento: "Alcotest Dräger", 
    cia: "PPTRAN - CIAOP - 17ºBPM - SEDE", 
    status: "Operacional", 
    marca: "Dräger", 
    modelo: "Alcotest", 
    patrimonioEtilometro: "100002385312",
    patrimonioImpressora: "100002379268",
    ultimaCalibracao: "10/10/2025", 
    proximaCalibracao: "10/10/2026", 
    numInmetro: "Portaria INMETRO", 
    responsavel: "Equipe PPTRAN / Trânsito", 
    observacoes: "Utilizado pelo Pelotão de Trânsito do 17º BPM nas operações e blitze." 
  },
  { 
    id: "ET-3970", 
    serie: "3970", 
    equipamento: "Alcotest Dräger", 
    cia: "PPTRAN - CIAOP - 17ºBPM - SEDE", 
    status: "Operacional", 
    marca: "Dräger", 
    modelo: "Alcotest", 
    patrimonioEtilometro: "100002378342",
    patrimonioImpressora: "100002379285",
    ultimaCalibracao: "10/10/2025", 
    proximaCalibracao: "10/10/2026", 
    numInmetro: "Portaria INMETRO", 
    responsavel: "Equipe PPTRAN / Trânsito", 
    observacoes: "Aparelho alocado no Pelotão de Trânsito." 
  }
];